[tasks."lint"]
alias = "l"
description = "Run clippy"
run = "cargo clippy"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml"]

[tasks."build"]
alias = "b"
run = "cargo build --release"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
outputs = ["target/release/colporteur"]

[tasks.test]
alias = "t"
description = "Run tests"
run = "cargo nextest run"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml", "tests/**/*"]

[tools]
"npm:docsify-cli" = "5.0.0"
"cargo:cargo-nextest" = "0.9.143"
"cargo:convco" = "0.7.2"
dprint = "0.57.4"
hk = "1.58.1"
pkl = "0.32.1"
rust = "1.98.1"
