[tasks."lint"]
alias = "l"
description = "Run clippy"
run = "cargo clippy"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml"]

[tasks."build"]
alias = "b"
run = "cargo build --release"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
outputs = ["target/release/colporteur"]

[tasks.test]
alias = "t"
description = "Run tests"
run = "cargo nextest run"
quiet = true
sources = ["src/**/*.rs", "Cargo.toml", "tests/**/*"]

[tools]
"cargo:cargo-nextest" = "latest"
"cargo:convco" = "latest"
dprint = "latest"
hk = "latest"
pkl = "latest"
rust = "latest"
