[tasks."lint"]
description = "Run clippy"
run = "cargo clippy"

[tasks."build"]
run = "cargo build --release"

[tasks.test]
description = "Run tests"
run = "cargo test"

[tools]
"cargo:convco" = "latest"
dprint = "latest"
hk = "latest"
pkl = "latest"
rust = "latest"
